apiVersion: v1
kind: Service
metadata:
  name: test-service #service name
spec:
  selector:
    app: test
  ports:
  - protocol: "TCP"
    port: 5001 
    nodePort: 31212
    targetPort: 5001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test #deployment name #should be same as app above
spec:
  selector:
    matchLabels:
      app: test #should be same as app above
  replicas: 1
  template:
    metadata:
      labels:
        app: test #should be same as app above
    spec:
      containers:
      - name: test #should be same as app above
        image: darveenvijayan/squared:v1 # the url from dockerhub
        imagePullPolicy: Always
        ports:
        - containerPort: 5001 #port from flask